config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Begin routes for all forms in Tiba
  resources :promotions, only: [:show] do
    resources :promo_quotes, only: [:create]
  end
  resources :newsletters, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :quotes, only: [:new, :create] do
    get 'find_appartements', on: :collection
  end
  # End


  resources :references, controller: "past_projects", only: [:index]

	resources :projects, only: [:index, :show] do
    get 'promotions', on: :collection
    get 'villas', on: :collection
    get 'apartments', on: :collection
    get 'commerces', on: :collection
    get 'lotissements', on: :collection
    get 'get_urls'
    get 'plan', on: :member
    resources :products, only: [:show]
    resources :credit_simulators, only: [:index]
  end

  get 'contact', to: 'static_pages#contact', as: 'contact'
  get 'service', to: 'static_pages#service', as: 'service'
  get 'about',   to: 'static_pages#about',   as: 'about'

  root 'static_pages#home'
end

app/views/shared/_footer.html.erb
<div class="row full-width">
  <div class="small-12 medium-4 medium-offset-1 columns">
    <h3>Inscription Newsletter</h3>

    <%= render 'newsletters/form' %>
  </div>
  <div class="small-12 medium-6 columns">
    <h3>Suivez nous</h3>

    <div class="social-media">
      <% @available_social_networks.each do |social_network| %>
        <% if social_network.activated %>
          <%= link_to social_network.url, target: '_blank' do %>
          <i class="fa fa-2x fa-<%= social_network.name %>"></i>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <div class="top">
    <ul class="title-area">
      <li class="name">
        <h1>
          <%= link_to image_tag('tiba_logo.png'), root_path %>
          <div id="nav-icon">
					  <span></span>
					  <span></span>
					  <span></span>
					  <span></span>
					  <span></span>
					  <span></span>
					</div>
        </h1>
      </li>
    </ul>

    <section class="top-bar-section l-effect-4">
      <ul class="phone-container">
        <li><i class="fa fa-phone-square"></i></li>
        <% if @phones.first.phone_numbers.present? %>
          <% @phones.first.phone_numbers.each do |phone| %>
            <li id="phone-num"> <%= phone.number %> </li>
          <% end %>
        <% else %>
          <li id="phone-num"> +216 71 23 27 35 </li>
        <% end %>

      </ul>
      <ul class="menu-right">
        <li class="menu">
          <%= active_link_to 'acceuil', root_path, active: [['static_pages'], ['home']] %>
        </li>
        <li class="menu">
          <%= active_link_to 'rechercher un bien', projects_path, id: "project", active: [['projects'], ['index']] %>
        </li>
				<li class="menu">
          <%= active_link_to 'nos services', service_path, active: [['static_pages'], ['service']] %>
        </li>
				<li class="menu">
          <%= active_link_to 'nos references', references_path, active: [['past_projects'], ['index']] %>
        </li>
        <li class="menu">
          <%= active_link_to 'qui somme nous', about_path, active: [['static_pages'], ['about']] %>
        </li>
        <li class="menu">
          <%= active_link_to 'contact', contact_path, active: [['static_pages'], ['contact']] %>
        </li>
      </ul>
    </section>
  </div>
</nav>

<div id="low-bar">
	<% if content_for?(:low_bar) %>
	  <%= yield(:low_bar) %>
	<% else %>
	  <ul>
      <%= active_link_to 'VILLAS', villas_projects_path, active: [['projects'], ['villas']], wrap_tag: :li %>
      <%= active_link_to 'APPARTEMENTS', apartments_projects_path, active: [['projects'], ['apartments']], wrap_tag: :li %>
      <%= active_link_to 'COMMERCES', commerces_projects_path, active: [['projects'], ['commerces']], wrap_tag: :li %>
      <%= active_link_to 'LOTISSEMENTS/TERRAINS', lotissements_projects_path, active: [['projects'], ['lotissements']], wrap_tag: :li %>
      <li class="project-form"> <%= render 'projects/search' %> </li>
      <li class="search"> <i class="fa fa-search" aria-hidden="true"></i></li>
		</ul>
	<% end %>
</div>

app/views/shared/_mobileHeader.html.erb
<section class="mobile-top top-bar-section l-effect-4">
  <ul class="menu-right">
    <li class="menu"><%= link_to 'ACCUEIL', root_path %></li>
    <li class="menu">
			<%= link_to "RECHERCHER UN BIEN", projects_path, id: "project" %>
      <% if @project %>
        <ul>
          <li class="low-menu"> <%= link_to @project.title , root_path %> </li>
        </ul>
      <% else %>
        <ul>
          <li class="low-menu"><%= link_to 'VILLA',villas_projects_path %></li>
     		  <li class="low-menu"><%= link_to 'APPARTEMENT',apartments_projects_path %></li>
          <li class="low-menu"><%= link_to 'COMMERCE',commerces_projects_path %></li>
          <li class="low-menu"><%= link_to 'LOTISSEMNET/TERRAIN',lotissements_projects_path %></li>
        </ul>
      <% end %>
    </li>
    <li class="menu">
      <%= active_link_to 'NOS SERVICES', service_path, active: [['static_pages'], ['service']] %>
    </li>
    <li class="menu">
      <%= active_link_to 'NOS REFERENCES', references_path, active: [['past_projects'], ['index']] %>
    </li>
    <li class="menu">
      <%= active_link_to 'QUI SOMMES NOUS', about_path, active: [['static_pages'], ['about']] %>
    </li>
    <li class="menu">
      <%= active_link_to 'CONTACT', contact_path, active: [['static_pages'], ['contact']] %>
    </li>
  </ul>
</section>

app/views/shared/_quote_form.html.erb
<input type="checkbox" id="togglebox" />
<div class="overlay"></div>

<nav id="offcanvas-menu">
  <label for="togglebox" id="close">  <i class="fa fa-angle-double-right" aria-hidden="true"></i></label>

  <%= render 'quotes/form'%>
</nav>
<label class="nav-action" for="togglebox">
  <ul>
    <li>
      <a class="devis-title">
        <span class="nav-icon">
          <span class="text">Demandes d'informations </span>
        </span>
      </a>
    </li>
  </ul>
</label>