config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Begin routes for all forms in Tiba
  resources :promotions, only: [:show] do
    resources :promo_quotes, only: [:create]
  end
  resources :newsletters, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :quotes, only: [:new, :create] do
    get 'find_appartements', on: :collection
  end
  # End


  resources :references, controller: "past_projects", only: [:index]

	resources :projects, only: [:index, :show] do
    get 'promotions', on: :collection
    get 'villas', on: :collection
    get 'apartments', on: :collection
    get 'commerces', on: :collection
    get 'lotissements', on: :collection
    get 'get_urls'
    get 'plan', on: :member
    resources :products, only: [:show]
    resources :credit_simulators, only: [:index]
  end

  get 'contact', to: 'static_pages#contact', as: 'contact'
  get 'service', to: 'static_pages#service', as: 'service'
  get 'about',   to: 'static_pages#about',   as: 'about'

  root 'static_pages#home'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                          :integer          not null, primary key
#  title                       :string
#  overview                    :text
#  description                 :text
#  location                    :string
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  plan_image_file_name        :string
#  plan_image_content_type     :string
#  plan_image_file_size        :integer
#  plan_image_updated_at       :datetime
#  category                    :string
#  slug                        :string
#  latitude                    :float
#  longitude                   :float
#  promotion_id                :integer
#  featured_image_file_name    :string
#  featured_image_content_type :string
#  featured_image_file_size    :integer
#  featured_image_updated_at   :datetime
#  video_url                   :string
#  map_url                     :string
#  rank                        :integer
#  available                   :boolean          default(TRUE)
#  plan_pdf_file_name          :string
#  plan_pdf_content_type       :string
#  plan_pdf_file_size          :integer
#  plan_pdf_updated_at         :datetime
#  brochure_pdf_file_name      :string
#  brochure_pdf_content_type   :string
#  brochure_pdf_file_size      :integer
#  brochure_pdf_updated_at     :datetime
#  max_surf                    :integer
#  min_surf                    :integer
#  min_price                   :integer
#  max_price                   :integer
#  min_room                    :integer
#  max_room                    :integer
#  nb_floor                    :integer
#  sold                        :boolean          default(FALSE)
#  show_area                   :boolean          default(TRUE)
#  show_price                  :boolean          default(TRUE)
#  show_room                   :boolean          default(TRUE)
#  show_floor                  :boolean          default(TRUE)
#  price                       :integer
#  vcard_file_name             :string
#  vcard_content_type          :string
#  vcard_file_size             :integer
#  vcard_updated_at            :datetime
#

class Project < ActiveRecord::Base
  extend FriendlyId

  PROJECT_CATEGORIES = ["villas","appartements","commerces","lotissements/terrains"]

  friendly_id :title, use: :slugged
  geocoded_by :location
  after_validation :geocode

  belongs_to :promotion
  has_one :album

  has_many :meta_configurations
  has_many :gallery_photos
  has_many :project_videos
  has_many :products

  scope :promotions, -> { where(promoted: true) }
  scope :villas, -> { where(category: "villas") }
  scope :apartments, -> { where(category: "appartements") }
  scope :commerces, -> { where(category: "commerces") }
  scope :lotissements, -> { where(category: "lotissements/terrains") }

  scope :project_order, -> { order(:rank) }
  scope :available, -> { where(available: true)}

  accepts_nested_attributes_for :project_videos, :allow_destroy => true

  has_attached_file :plan_image, styles: { medium: "300x300>", thumb: "100x100>", large: "1280x1000>" }, default_url: "/images/:style/missing.png"
  has_attached_file :featured_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :plan_image, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\Z/

  has_attached_file :plan_pdf
  validates_attachment :plan_pdf, :content_type => { :content_type => %w(application/pdf), message: "Vous devez inserer un document de format PDF" }

  has_attached_file :brochure_pdf
  validates_attachment :brochure_pdf, :content_type => { :content_type => %w(application/pdf), message: "Vous devez inserer un document de format PDF" }

  validates_attachment_presence :plan_image
  validates_attachment_presence :featured_image

  accepts_nested_attributes_for :gallery_photos, allow_destroy: true

  validates :title, :description, :location, :category, presence: true
  scope :not_sold, -> { eager_load(:products).where('products.sold = ? OR projects.sold = ? ', false, false).uniq }
end

app/controllers/projects_controller.rb
# == Schema Information
#
# Table name: projects
#
#  id                          :integer          not null, primary key
#  title                       :string
#  overview                    :text
#  description                 :text
#  location                    :string
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  plan_image_file_name        :string
#  plan_image_content_type     :string
#  plan_image_file_size        :integer
#  plan_image_updated_at       :datetime
#  category                    :string
#  slug                        :string
#  latitude                    :float
#  longitude                   :float
#  promotion_id                :integer
#  featured_image_file_name    :string
#  featured_image_content_type :string
#  featured_image_file_size    :integer
#  featured_image_updated_at   :datetime
#  video_url                   :string
#  map_url                     :string
#  rank                        :integer
#  available                   :boolean          default(TRUE)
#  plan_pdf_file_name          :string
#  plan_pdf_content_type       :string
#  plan_pdf_file_size          :integer
#  plan_pdf_updated_at         :datetime
#  brochure_pdf_file_name      :string
#  brochure_pdf_content_type   :string
#  brochure_pdf_file_size      :integer
#  brochure_pdf_updated_at     :datetime
#  max_surf                    :integer
#  min_surf                    :integer
#  min_price                   :integer
#  max_price                   :integer
#  min_room                    :integer
#  max_room                    :integer
#  nb_floor                    :integer
#  sold                        :boolean          default(FALSE)
#  show_area                   :boolean          default(TRUE)
#  show_price                  :boolean          default(TRUE)
#  show_room                   :boolean          default(TRUE)
#  show_floor                  :boolean          default(TRUE)
#  price                       :integer
#  vcard_file_name             :string
#  vcard_content_type          :string
#  vcard_file_size             :integer
#  vcard_updated_at            :datetime
#

class ProjectsController < ApplicationController
  def index
    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true).available.project_order
    @projects_header = ProjectsHeader.first
  end

  def get_urls
    @project = Project.find(params[:project_id])
    respond_to do |format|
      format.js {}
    end
  end

  def plan
    @project = Project.friendly.find(params[:id])
    respond_to do |format|
     format.pdf do
       render pdf: "#{@project.title}-plan", # pdf will download as my_pdf.pdf
       layout: 'pdf'
     end
   end
  end

  def show
  	@project = Project.friendly.find(params[:id])
    @gallery_photos = @project.gallery_photos
    @project_videos = @project.project_videos
    @project_meta = @project.meta_configurations
    @search = @project.products.ransack(params[:q])
    @products = @search.result(distinct: true).product_order

    session[:last_project_page] = request.env['HTTP_REFERER'] || projects_path

    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def find_appartements
    @product = Product.where project_id: params[:project_id]
    respond_to do |format|
      format.js {}
    end
  end

  def promotions
    @projects = Project.promotions.project_order
  end

  def villas
    @projects = Project.villas.available.project_order
    @category_header = Testimonial.villas.first
  end

  def apartments
    @projects = Project.apartments.available.project_order
    @category_header = Testimonial.apartments.first
  end

  def commerces
    @projects = Project.commerces.available.project_order
    @category_header = Testimonial.commerces.first
  end

  def lotissements
    @projects = Project.lotissements.available.project_order
    @category_header = Testimonial.lotissements.first
  end


end

app/helpers/projects_helper.rb
# == Schema Information
#
# Table name: projects
#
#  id                          :integer          not null, primary key
#  title                       :string
#  overview                    :text
#  description                 :text
#  location                    :string
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  plan_image_file_name        :string
#  plan_image_content_type     :string
#  plan_image_file_size        :integer
#  plan_image_updated_at       :datetime
#  category                    :string
#  slug                        :string
#  latitude                    :float
#  longitude                   :float
#  promotion_id                :integer
#  featured_image_file_name    :string
#  featured_image_content_type :string
#  featured_image_file_size    :integer
#  featured_image_updated_at   :datetime
#  video_url                   :string
#  map_url                     :string
#  rank                        :integer
#  available                   :boolean          default(TRUE)
#  plan_pdf_file_name          :string
#  plan_pdf_content_type       :string
#  plan_pdf_file_size          :integer
#  plan_pdf_updated_at         :datetime
#  brochure_pdf_file_name      :string
#  brochure_pdf_content_type   :string
#  brochure_pdf_file_size      :integer
#  brochure_pdf_updated_at     :datetime
#  max_surf                    :integer
#  min_surf                    :integer
#  min_price                   :integer
#  max_price                   :integer
#  min_room                    :integer
#  max_room                    :integer
#  nb_floor                    :integer
#  sold                        :boolean          default(FALSE)
#  show_area                   :boolean          default(TRUE)
#  show_price                  :boolean          default(TRUE)
#  show_room                   :boolean          default(TRUE)
#  show_floor                  :boolean          default(TRUE)
#  price                       :integer
#  vcard_file_name             :string
#  vcard_content_type          :string
#  vcard_file_size             :integer
#  vcard_updated_at            :datetime
#

module ProjectsHelper
  def grid_size_for(projects)
    return projects.size % 3 == 0 ? '3' : '2'
  end

  def gallery_size_for(photos)
    if photos.size <= 2
      return '2'
    else
      return '3'
    end
  end

  def set_filter(value, default)
   value.nil? ? default : value
  end

  def span_value_for(project)
    shown_filters = [project.show_room, project.show_floor, project.show_area, project.show_price].select do |element|
        element == true
    end

    return 12 / shown_filters.size
  end

  def plan_hint(obj)
    if obj.plan_pdf?
      content_tag :span do
        concat('PDF actuel:')
        concat(link_to(obj.plan_pdf_file_name, obj.plan_pdf.url, target: '_blank'))
      end
    end
  end

  def brochure_hint(obj)
    if obj.brochure_pdf?
      content_tag :span do
        concat('PDF actuel:')
        concat(link_to(obj.brochure_pdf_file_name, obj.brochure_pdf.url, target: '_blank'))
      end
    end
  end
end

app/views/projects/_filters.html.erb
<div class="row filter-op">
	<% if @project.show_area %>
		<div class="large-<%= span_value_for(@project) %> columns">
				<div class="small-10 small-offset-1 large-10 large-offset-2 filter-container">
					<div class="row">
						<div class="small-4 large-5 columns">
							<span class="filter-cat">Surface</span>
						</div>
						<div class="small-8 large-7 columns">
							<div class="slider-surf">
						  	<span type="text" class="min-surf">
									<%= set_filter( @project.min_surf, 1000) %>
								</span>
				     		<span  type="text" class="max-surf">
									<%=  set_filter( @project.max_surf, 10000 ) %>
								</span>
							</div>
						</div>
					</div>
				</div>
		</div>
	<% end %>
	<% if @project.show_room %>
		<div class="large-<%= span_value_for(@project) %> columns">
			<div class="small-10 small-offset-1 large-10 large-offset-2 filter-container">
				<div class="row">
					<div class="small-4 large-5 columns">
						<span class="filter-cat">Piéces</span>
					</div>
					<div class="small-8 large-7 columns">
						<div class="slider-rooms">
					  	<span type="text" class="min-rooms">
								<%= set_filter( @project.min_room , 1 ) %>
							</span>
			     		<span type="text" class="max-rooms">
								<%= set_filter( @project.max_room , 12) %>
							</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
	<% if @project.show_price %>
		<div class="large-<%= span_value_for(@project) %> columns">
			<div class="small-10 small-offset-1 large-10 large-offset-2 filter-container">
				<div class="row">
					<div class="small-4 large-5 columns">
						<span class="filter-cat">Prix</span>
					</div>
					<div class="small-8 large-7 columns">
						<div class="slider-price">
							<span type="text" class="min-price">
								<%= set_filter( @project.min_price, 300) %>
							</span>
							<span type="text" class="max-price">
								<%= set_filter( @project.max_price , 10000) %>
							</span>
						</div>
					</div>
				</div>
			</div>
		</div>
	<% end %>
	<% if @project.show_floor %>
		<div class="large-<%= span_value_for(@project) %> columns">
			<div class="row">
				<div class="small-10 small-offset-1 filter-container">
					<div class="small-4 large-5 columns">
						<span class="filter-cat">Étages</span>
					</div>
					<div class="small-8 large-7 columns">
						<input class="num-floor" type="number" min="0" max="<%= set_filter( @project.nb_floor, 12) %>">
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

<%= search_form_for @search, url: project_path(@project), remote: true do |f| %>
  <%= f.hidden_field :superficie_gteq, placeholder: "Min Surface" %>
  <%= f.hidden_field :superficie_lteq, placeholder: "Max Surface" %>
	<%= f.hidden_field :configuration_gteq, placeholder: "Min Room" %>
  <%= f.hidden_field :configuration_lteq, placeholder: "Max Room" %>
	<%= f.hidden_field :price_gteq, placeholder: "Min Price" %>
	<%= f.hidden_field :price_lteq, placeholder: "Max Price" %>
	<%= f.hidden_field :floor_eq, placeholder: "Floor" %>
<% end %>

app/views/projects/_infos.html.erb
<div class="project-infos modal">
	<div class="row intro">
  	<%= image_tag 'close.png', class: 'close' %>
    <h1 class="text-centered"><%= project.title %></h1>
    <div class="row">
      <p class="description text-centered">
      	<%= project.description %>
      </p>
    </div>
  </div>
</div>
<div class="project-plan modal">
	<div class="container">
		<div class="row">
			<div class="small-centered medium-centered large-centered medium-12 large-12 columns">
				<%= image_tag 'close.png', class: 'close' %>
				<div class="image-holder">
					<%= image_tag project.plan_image.url %>
				</div>
			</div>
		</div>
  </div>
</div>
<div class="project-map modal">
	<div class="row intro">
    <div class="small-centered medium-centered large-centered medium-12 large-12 columns">
      <%= image_tag 'close.png', class: 'close' %>
    	<div class="map">
    	  <div id='map-<%= project_id %>' class="map-element" >
    	  </div>
    	</div>
    </div>
  </div>
</div>

app/views/projects/_level.html.erb
<div class="level-container">
	<div class="image-wrapper">	
		<%= image_tag 'filter.png', class:"image-filter" %>
		<div class="ribbon-level">
		  <i>
		    <span class="level">4.</span>
		  </i>
		</div>
	</div>
</div>

app/views/projects/_modals.html.erb
<div class="md-modal md-effect-12" id="modal-description-<%= project.id %>">
	<div class="md-content">
		<h3><%= project.title.capitalize %></h3>
		<div>
			<p><%= raw( project.description)%><p>
			<span class="md-close"></span>
		</div>
	</div>
</div>

<div class="md-modal md-effect-12" id="modal-plan-<%= project.id %>">
	<div class="md-content">
		<h3><%= project.title.capitalize %></h3>
		<div>

			<%= link_to '#', data: { 'reveal-id': 'plan-modal', 'plan-id': project.plan_image.url(:large)}, class:"zoom-plan", remote: true do %>
				<%= image_tag project.plan_image.url %>
			<% end %>
			<!--  The code below generate Pdf with wicked_pdf or display attached Pdf related to plan -->
			<% if  project.plan_pdf.present? %>
				<%= link_to project.plan_pdf.url(:original, false), target: '_blank' do %>
					<span data-tooltip data-tooltip data-options="disable_for_touch:true"
								aria-haspopup="true" class=" md-download has-tip" title="download PDF"
					>
						<i class="fa fa-file-pdf-o"></i>
						Télécharger le plan
					</span>
				<% end %>
			<% else %>
				<%= link_to plan_project_path(project, format: :pdf), target: '_blank' do %>
					<span data-tooltip data-tooltip data-options="disable_for_touch:true"
								aria-haspopup="true" class=" md-download has-tip" title="download PDF"
					>
						<i class="fa fa-file-pdf-o"></i>
						Télécharger le plan
					</span>
				<% end %>
			<% end %>
			<span class="md-close"></span>
		</div>
		<div id="plan-modal" class="reveal-modal large" data-reveal>
			<%= image_tag project.plan_image.url(:large), class: "zoom-image" %>
			<span class="close-reveal-modal"> </span>
		</div>
	</div>
</div>

<div class="md-modal md-effect-12" id="modal-localisation-<%= project.id %>">
	<div class="md-content">
		<h3><%= project.title.capitalize %></h3>
		<div>
			<div style='width: 100%;'>
				<iframe src="<%= project.map_url %>" id="map-<%= project.id %>" style='width: 100%; height: 400px;'></iframe>
			</div>
			<span class="md-close"></span>
		</div>
	</div>
</div>

<% if project.video_url.present? %>
	<div class="md-modal md-effect-12" id="modal-video-<%= project.id %>">
		<div class="md-content">
			<h3><%= project.title.capitalize %></h3>
			<div>
				<div class="flex-video widescreen">
	        <iframe id="video-<%= project.id %>" width="420" height="315" src="" frameborder="0" allowfullscreen></iframe>
				</div>
				<span class="md-close"></span>
			</div>
		</div>
	</div>
<% end %>


<!-- <script type="text/javascript">
	window["handler-<%= project.id %>"] = Gmaps.build('Google');
	window["handler-<%= project.id %>"].buildMap({
	    provider: {
	      disableDefaultUI: true
	      // pass in other Google Maps API options here
	    },
	    internal: {
	      id: 'map-<%= project.id %>'
	    }
	  },
	  function(){
	    markers = window["handler-<%= project.id %>"].addMarkers([
	      {
	        "lat": <%= project.latitude %>,
	        "lng": <%= project.longitude %>
	      }
	    ]);
	    window["handler-<%= project.id %>"].bounds.extendWith(markers);
	    window["handler-<%= project.id %>"].fitMapToBounds();
			window["handler-<%= project.id %>"].getMap().setZoom(12);
	  }
	);
</script> -->

app/views/projects/_project.html.erb
<% content_for :modals do %>
  <%= render partial: 'modals', locals: { project: project } %>
<% end %>

<li class="project">

  <div class="project-image-container">
    <div class="project-details">
      <%= image_tag project.featured_image.url, class: "project-image" %>
      <div class="project-controls">
        <span class="expand md-trigger has-tip tip-top" data-modal="modal-description-<%= project.id %>" data-tooltip data-options="disable_for_touch:true" aria-haspopup="true" title="Description technique">
          <%= image_tag "blueprint.png" %>
        </span>
        <span class="expand md-trigger has-tip tip-top" data-modal="modal-plan-<%= project.id %>" data-tooltip data-options="disable_for_touch:true" aria-haspopup="true" title="Plan">
          <%= image_tag "plan-icon.png" %>
        </span>
        <span class="expand md-trigger has-tip tip-top" data-modal="modal-localisation-<%= project.id %>" data-tooltip data-options="disable_for_touch:true" aria-haspopup="true" title="Localisation">
          <%= image_tag "map-location.png" %>
        </span>
        <%= link_to project_path(project), class: "expand has-tip tip-top", data: {tooltip: "", options: "disable_for_touch:true"}, aria: {haspopup: "true"}, title: "Découvrir ..." do %>
        <%= image_tag "more.png" %>
        <% end %>
      </div>
    </div>
    <% if project.video_url.present? %>
      <%= link_to project_get_urls_path(project.id), remote: true do %>
        <%= image_tag "360.jpg", class: "project-video md-trigger", data: {modal: "modal-video-#{project.id}"} %>
      <% end %>
    <% end %>
  </div>
  <% if browser.device.mobile? %>
    <div class="project-image-container">
      <div class="project-details">
        <div class="mobile-projects-controls">
          <span class="mobile-infos md-trigger has-tip tip-top" data-modal="modal-description-<%= project.id %>" data-tooltip data-options="disable_for_touch:true" aria-haspopup="true" title="Description technique">
            <%= image_tag "blueprint.png" %>
          </span>
          <span class="mobile-infos md-trigger has-tip tip-top" data-modal="modal-plan-<%= project.id %>" data-tooltip data-options="disable_for_touch:true" aria-haspopup="true" title="Plan">
            <%= image_tag "plan-icon.png" %>
          </span>
          <span class="mobile-infos md-trigger has-tip tip-top" data-modal="modal-localisation-<%= project.id %>" data-tooltip data-options="disable_for_touch:true" aria-haspopup="true" title="Localisation">
            <%= image_tag "map-location.png" %>
          </span>
          <%= link_to project_path(project), class: "mobile-infos has-tip tip-top", data: {tooltip: "", options: "disable_for_touch:true"}, aria: {haspopup: "true"}, title: "Découvrir ..." do %>
          <%= image_tag "more.png" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <h3 class="project-title"><%= project.title.capitalize %></h3>
</li>

app/views/projects/_search.html.erb
<%= search_form_for @q, url: projects_path do |f| %>
  <%= f.text_field :title_or_category_cont, class: "search-field", placeholder: "Nom du projet ou catégorie" %>
<% end %>

app/views/projects/apartments.html.erb
<% title "Appartement neuf et haut standing" %>
<% meta_tag :description, "Achat / vente d'appartements aux Jardins de Carthage
    et au Lac 2. Découvrez la description technique, le plan et la localisation de nos appartements."
%>

<%= render'projects/testimonial' %>
<div class="projects">
  <div class="row">
    <ul class="small-block-grid-1 large-block-grid-<%= grid_size_for(@projects) %>">
      <%= render @projects %>
    </ul>
  </div>
</div>

app/views/projects/commerces.html.erb
<% title "Immeuble de bureaux Haut standing" %>
<% meta_tag :description, "Achat / Vente de bureaux et commerces à La Goulette,
     au Belvédère, au Centre Urbain Nord et au Lac 2. "
%>

<%= render'projects/testimonial' %>
<div class="projects">
  <div class="row">
    <ul class="small-block-grid-1 large-block-grid-<%= grid_size_for(@projects) %>">
      <%= render @projects %>
    </ul>
  </div>
</div>

app/views/projects/index.html.erb
<% title "Réalisation, projets et conseils" %>
<% meta_tag :description, "Tiba immobilière innove et met a votre disposition
   un éventail de conseils et de services pour bien choisir votre bien immobilier."
%>

<section class="projects-header" style="background: url(<%= @projects_header.image.url %>) no-repeat center center;">
  <div class="row intro">
    <div class="small-centered medium-centered large-centered medium-12 large-12 columns">
      <%= simple_format @projects_header.content %>
    </div>
    <div class="mouse">
	    <span></span>
	    <i class="fa fa-angle-double-down fa-4x scroll-down"></i>
	  </div>

  </div>
</section>

<div class="projects">
  <div class="row">
    <ul class="large-block-grid-<%= grid_size_for(@projects) %> small-block-grid-1">
      <%= render @projects %>
    </ul>
  </div>
</div>

app/views/projects/lotissements.html.erb
<% title "Lotissements de terrain" %>
<% meta_tag :description, "Achat / Vente de terrains à Soliman et à Tebourba.
    Lotissements viabilisés qui vous donnera l'envie de construire la maison de vos rêves. "
%>

<%= render'projects/testimonial' %>
<div class="projects">
  <div class="row">
    <ul class="small-block-grid-1 large-block-grid-<%= grid_size_for(@projects) %>">
      <%= render @projects %>
    </ul>
  </div>
</div>

app/views/projects/plan.pdf.erb
<%= javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
<script>
    $(document).ready(function() {
      $('h1').css({
         'text-align' : 'center',
         'text-transform' : 'capitalize'
      });
      $('.image-holder').css({
        'position': 'relative'
      });
      $('.wicked-img').css({
        'position': 'absolute',
        'transform': 'translateY(30%)'
      });
  });
</script>

<div>
  <h1> <%= @project.title %> </h1>
  <div class="image-holder">
    <%= wicked_pdf_image_tag @project.plan_image.url, class: 'wicked-img' %>
  </div>
</div>

app/views/projects/promotions.html.erb
<% if @projects.present? %>
  <%= render @projects %>
<% else %>
  <%= render template:'static_pages/empty' %>
<% end %>

app/views/projects/show.html.erb
<% if @project_meta.first.present? %>
	<% title @project_meta.first.title %>
	<% meta_tag :description, @project_meta.first.description %>
<% end %>

<% content_for :title do %>
	Tiba - <%= @project.title %>
<% end %>

<% content_for :low_bar do %>
	<% if session[:last_project_page] %>
		<%= link_to  session[:last_project_page], class: 'back' do %>
			<%= image_tag('chevron.png') %>
		<% end %>
	<% end %>
	<ul>
	 <li><%= @project.title %></li>
	</ul>
<% end %>

<div class="section-infos">
	<div class="name">
		<h1 class="title"><%= @project.title.titleize %></h1>
	</div>

	<div class="row">
		<div class="large-8 columns">
			<div class="related-infos" style="text-align: left;">
				<%= raw(@project.description) %>
			</div>
			<% if  @project.brochure_pdf.present? %>
				<%= link_to @project.brochure_pdf.url(:original, false), class: 'related-pdf', target: '_blank' do %>
						<i class="fa fa-file-pdf-o"></i>
						Télécharger la brochure
				<% end %>
			<% end %>
		</div>
		<div class="large-3 large-offset-1 columns">
			<a href="#" class="button btn-doc" id="doc-project" data-project="<%= @project.id %>">Demander un dossier </a>
			<% if @project.price.present? %>
				<%= link_to  project_credit_simulators_path(@project), class: "button btn-credit" do %>
					Calculer le crédit
				<% end %>
			<% end %>
		</div>
	</div>
</div>

<div class="contain-to-grid">
	<div class="row">
		<ul class="large-block-grid-<%= gallery_size_for(@gallery_photos) %> small-block-grid-1" >
			<% @gallery_photos.each do |gallery_photo| %>
			<li>
				<%= link_to '#', class: "gallery-link", data: { 'reveal-id': 'gallery-modal', 'photo-id': gallery_photo.id}, remote: true do %>
						<%= image_tag gallery_photo.photo.url, class: "project-gallery" %>
				<% end %>
			</li>
			<% end %>
			<br/>

			<% @project_videos.each do |video| %>
				<li>
					<div class="video-holder flex-video">
						<iframe src=""></iframe>
						<a class="video-url" href="<%= video.video_url %>" target="_blank">
						</a>
					</div>
				</li>
			<% end %>
		</ul>

	</div>
</div>

<div id="gallery-modal" class="reveal-modal large project-gallery" data-reveal>
	<ul data-orbit
	 	class="modal-orbit"
		data-options="animation:slide;
                  pause_on_hover:false;
                  animation_speed:500;
                  navigation_arrows:true;
                  bullets:true;"
	>
		<% @gallery_photos.each do |gallery_photo| %>
			<li id="photo-<%= gallery_photo.id %>" class="">
				<%= image_tag gallery_photo.photo.url %>
			</li>
		<% end %>
	</ul>

	<span class="close-reveal-modal"> </span>
</div>

<% if @products.present? %>
	<div class="row">
		<div class="section-filter">
			<div class="row">
				<span class="filter-title">Objets en ventes</span>
				<%= render partial: 'filters' %>
			</div>

			<div class="row">
				<div class="small-10 small-offset-1 large-10 end " id="appatements-holder">
					<%= render @products %>
				</div>
			</div>

		</div>
	</div>
<% end %>
<% if !@products.present? && !@gallery_photos.present? %>
	<div class="row">
		<div class="section-filter">
			<%= image_tag 'logo.jpg', class: "tiba-logo" %>
		</div>
	</div>
<% end %>

app/views/projects/show.js.erb
<% if @products.empty? %>
  $('#appatements-holder').html("<p> Aucun produit ne satisfait cette recherche </p>");
<% else %>
  $('#appatements-holder').html("<%= j(render @products) %>");
<% end %>