config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Begin routes for all forms in Tiba
  resources :promotions, only: [:show] do
    resources :promo_quotes, only: [:create]
  end
  resources :newsletters, only: [:new, :create]
  resources :contacts, only: [:new, :create]
  resources :quotes, only: [:new, :create] do
    get 'find_appartements', on: :collection
  end
  # End


  resources :references, controller: "past_projects", only: [:index]

	resources :projects, only: [:index, :show] do
    get 'promotions', on: :collection
    get 'villas', on: :collection
    get 'apartments', on: :collection
    get 'commerces', on: :collection
    get 'lotissements', on: :collection
    get 'get_urls'
    get 'plan', on: :member
    resources :products, only: [:show]
    resources :credit_simulators, only: [:index]
  end

  get 'contact', to: 'static_pages#contact', as: 'contact'
  get 'service', to: 'static_pages#service', as: 'service'
  get 'about',   to: 'static_pages#about',   as: 'about'

  root 'static_pages#home'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id                           :integer          not null, primary key
#  name                         :string
#  overview                     :text
#  superficie                   :integer
#  configuration                :integer
#  floor                        :integer
#  project_id                   :integer
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  sold                         :boolean          default(FALSE), not null
#  slug                         :string
#  price                        :decimal(, )
#  plan_image_file_name         :string
#  plan_image_content_type      :string
#  plan_image_file_size         :integer
#  plan_image_updated_at        :datetime
#  description_technique        :text
#  document_pdf_file_name       :string
#  document_pdf_content_type    :string
#  document_pdf_file_size       :integer
#  document_pdf_updated_at      :datetime
#  rank                         :integer
#  picture_file_name            :string
#  picture_content_type         :string
#  picture_file_size            :integer
#  picture_updated_at           :datetime
#  related_picture_file_name    :string
#  related_picture_content_type :string
#  related_picture_file_size    :integer
#  related_picture_updated_at   :datetime
#  product_plan_file_name       :string
#  product_plan_content_type    :string
#  product_plan_file_size       :integer
#  product_plan_updated_at      :datetime
#

class Product < ActiveRecord::Base
  belongs_to :project

  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, :overview, :superficie, :configuration,
            :floor, :project, :description_technique, presence: true

  has_attached_file :document_pdf
  validates_attachment :document_pdf, :content_type => { :content_type => %w(application/pdf), message: "Vous devez inserer un document de format PDF" }

  has_attached_file :related_picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :related_picture, content_type: /\Aimage\/.*\Z/

  APPARTEMENT_CONFIG = 1..10

  has_attached_file :plan_image, styles: { medium: "300x300>", thumb: "100x100>", large: "1280x1000>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :plan_image, content_type: /\Aimage\/.*\Z/
  validates_attachment_presence :plan_image

  scope :product_order, -> { order(:rank) }
end

app/controllers/products_controller.rb
# == Schema Information
#
# Table name: products
#
#  id                           :integer          not null, primary key
#  name                         :string
#  overview                     :text
#  superficie                   :integer
#  configuration                :integer
#  floor                        :integer
#  project_id                   :integer
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  sold                         :boolean          default(FALSE), not null
#  slug                         :string
#  price                        :decimal(, )
#  plan_image_file_name         :string
#  plan_image_content_type      :string
#  plan_image_file_size         :integer
#  plan_image_updated_at        :datetime
#  description_technique        :text
#  document_pdf_file_name       :string
#  document_pdf_content_type    :string
#  document_pdf_file_size       :integer
#  document_pdf_updated_at      :datetime
#  rank                         :integer
#  picture_file_name            :string
#  picture_content_type         :string
#  picture_file_size            :integer
#  picture_updated_at           :datetime
#  related_picture_file_name    :string
#  related_picture_content_type :string
#  related_picture_file_size    :integer
#  related_picture_updated_at   :datetime
#  product_plan_file_name       :string
#  product_plan_content_type    :string
#  product_plan_file_size       :integer
#  product_plan_updated_at      :datetime
#

class ProductsController < ApplicationController

  def show
  	@product = Product.friendly.find(params[:id])
    session[:related_project_page] = request.env['HTTP_REFERER'] || project_path(@product.project)

  end

  def find_appartements
    @product_id = Product.where project_id: params[:project_id]
    respond_to do |format|
      format.js {}
    end
    @product = Product.friendly.find(params[:id])
  end

end

app/helpers/products_helper.rb
# == Schema Information
#
# Table name: products
#
#  id                           :integer          not null, primary key
#  name                         :string
#  overview                     :text
#  superficie                   :integer
#  configuration                :integer
#  floor                        :integer
#  project_id                   :integer
#  created_at                   :datetime         not null
#  updated_at                   :datetime         not null
#  sold                         :boolean          default(FALSE), not null
#  slug                         :string
#  price                        :decimal(, )
#  plan_image_file_name         :string
#  plan_image_content_type      :string
#  plan_image_file_size         :integer
#  plan_image_updated_at        :datetime
#  description_technique        :text
#  document_pdf_file_name       :string
#  document_pdf_content_type    :string
#  document_pdf_file_size       :integer
#  document_pdf_updated_at      :datetime
#  rank                         :integer
#  picture_file_name            :string
#  picture_content_type         :string
#  picture_file_size            :integer
#  picture_updated_at           :datetime
#  related_picture_file_name    :string
#  related_picture_content_type :string
#  related_picture_file_size    :integer
#  related_picture_updated_at   :datetime
#  product_plan_file_name       :string
#  product_plan_content_type    :string
#  product_plan_file_size       :integer
#  product_plan_updated_at      :datetime
#

module ProductsHelper
  def document_hint(obj)
    if obj.document_pdf?
      content_tag :span do
        concat('PDF actuel:')
        concat(link_to(obj.document_pdf_file_name, obj.document_pdf.url, target: '_blank'))
      end
    end
  end
end

app/views/products/_product.html.erb
<%= link_to project_product_path(@project, product) do %>
	<div class="row filter-result">
		<div class="large-4 small-12 columns">
			<div class="image-wrapper">
				<% if product.related_picture.present? %>
					<%= image_tag product.related_picture.url, class: "project-gallery" %>
				<% else %>
					<%= image_tag 'villa-level.jpg' %>
					<div class="ribbon-level">
						<i>
							<span class="level"><%= product.floor %>.</span>
						</i>
					</div>
				<% end %>
			</div>
		</div>
		<div class="large-8 small-12 columns filter-result-infos">
			<% if product.sold %>
			<div class="ribbon">Vendu </div>
			<% end %>
			<span class="filter-result-title"><%= product.name.titleize %> - <%= product.configuration %> Piéces</span>
			<div class="filter-result-descrip">
				<%= raw(product.overview)%>
			</div>
		</div>
	</div>
<% end %>

app/views/products/show.html.erb
<% content_for :low_bar do %>
	<% if session[:related_project_page] %>
		<%= link_to  session[:related_project_page], class: 'back' do %>
				<%= image_tag('chevron.png') %>
		<% end %>
	<% end %>
	<ul>
    <li> <%= link_to @product.project.title ,project_path(@product.project)%> </li>
	</ul>
<% end %>
<div id="product-holder" class="contain-to-grid">

  <div class="large-10 large-offset-2 head">
    <h1 class="title"><%= @product.name.titleize %></h1>
  </div>

  <div class="row">
    <div class="section-infos">
      <div class="medium-3 large-4 columns">
        <div class="row">
  				<div class="medium-12 large-10 columns end">
						<% if @product.related_picture.present? %>
							<%= image_tag @product.related_picture.url, class: "project-gallery" %>
						<% else %>
	  					<div class="image-wrapper">
	  						<%= image_tag 'villa-level.jpg' %>
	  						<div class="ribbon-level">
	  						  <i>
	  						    <span class="level"><%= @product.floor %>.</span>
	  						  </i>
	  						</div>
	  					</div>
	  					<span class="descrip"> <%= @product.floor %> Étages Balcon <%= @product.superficie %>m<sup>2</sup> </span>
						<% end %>
					</div>
  			</div>
      </div>
    </div>
    <div class="medium-3 large-8 columns">
      <div class="row">
        <div class="app-infos">
          <p class="app-related-infos">
						<%= raw(@product.overview)%>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="app-doc">
          <a href="#" class="button btn-doc" data-product="<%= @product.id %>" data-project="<%= @product.project_id %>" id="doc-product"> Demander un dossier </a>
        </div>
      </div>
      <div class="row">
        <h2 class="subtitle"> Plan de l'appartement </h2>
				<%= link_to '#', data: { 'reveal-id': 'plan-modal', 'plan-id': @product.plan_image.url(:large)}, class:"zoom-plan", remote: true do %>
					<%= image_tag @product.plan_image.url, class: 'image-centered' %>
				<% end %>
      </div>
      <div class="app-tech-infos">
        <div class="row">
						<div class="tech-infos-header">
							<h2 class="subtitle"> Descriptif </h2>
							<% if @product.document_pdf.present? %>
								<%= link_to @product.document_pdf.url(:original, false), target: "_blank" do %>
									<i class="fa fa-file-pdf-o fa-2x" ></i>
								<% end %>
							<% end %>

						</div>
              <p class="tech-infos">
                <%= @product.description_technique %>
              </p>
            </div>
          </div>
      </div>
    </div>
		<div id="plan-modal" class="reveal-modal large" data-reveal>
			<%= image_tag @product.plan_image.url(:large), class: "zoom-image" %>
			<span class="close-reveal-modal"> </span>
		</div>
  </div>
</div>